replace same tag default outbound handler
v2fly/v2ray-core pull request #1437
Opened 2021-12-02 09:05 UTC by XGFan

example config:
```
{
  "outbounds": [
    {
      "protocol": "vmess",
      "tag": "tagA"
    },
    {
      "protocol": "vmess",
      "tag": "tagA"
    }
  ]
}
```
first tagA outbound will be default outbound, the second outbound will replace first one in `taggedHandler `.
it looks weird.  like a orphan outbound.

2021-12-02 09:06 UTC, XGFan commented
#1435

2021-12-03 05:10 UTC, AkinoKaede approved these changes

2021-12-03 13:30 UTC, kallydev approved these changes

2021-12-04 13:42 UTC, nekohasekai requested changes
I think v2ray-core should refuse to accept duplicate tags, or at least show a warning.

2021-12-04 15:49 UTC, XGFan commented
> I think v2ray-core should refuse to accept duplicate tags, or at least show a warning.

accept duplicate tag handler will make 'update handler config by tag / implement command.OutboundOperation'  easier.

2021-12-10 13:15 UTC, nekohasekai approved these changes

2021-12-11 03:22 UTC, merged

2021-12-11 03:22 UTC, kslr commented
Thanks for your works.