Separate TcpKeepAliveIdle and TcpKeepAliveInterval check logic
v2fly/v2ray-core pull request #1484
Opened 2021-12-23 12:14 UTC by ValdikSS

This patch allows to separately configure both parameters.

2021-12-27 03:45 UTC, kslr approved these changes

2021-12-31 21:08 UTC, xiaokangwang approved these changes

2022-01-03 00:56 UTC, database64128 requested changes

2022-01-03 00:56 UTC, database64128 commented on transport/internet/sockopt_darwin.go
> +	sysTCP_KEEPINTVL = 0x101 // nolint: revive,stylecheck
Which darwin architectures are missing `TCP_KEEPINTVL`? We are using `x/sys/unix` here, not `syscall`, please double check.

2022-01-03 00:56 UTC, database64128 commented on transport/internet/sockopt_darwin.go
> +				}
I think moving `setsockopt(TCP_KEEPALIVE)` and `setsockopt(TCP_KEEPINTVL)` out of the `if config.TcpKeepAliveIdle > 0 || config.TcpKeepAliveInterval > 0` block would make it more readable.

2022-01-03 12:15 UTC, ValdikSS commented on transport/internet/sockopt_darwin.go
> +	sysTCP_KEEPINTVL = 0x101 // nolint: revive,stylecheck
I've copied this from https://github.com/golang/go/blob/master/src/net/tcpsockopt_darwin.go

2022-01-03 12:48 UTC, database64128 commented on transport/internet/sockopt_darwin.go
> +	sysTCP_KEEPINTVL = 0x101 // nolint: revive,stylecheck
That's not where you should be looking at.

https://github.com/golang/sys/blob/1d35b9e2eb4edf581781c7f3e2a36fac701f0a24/unix/zerrors_darwin_amd64.go#L1459

https://github.com/golang/sys/blob/1d35b9e2eb4edf581781c7f3e2a36fac701f0a24/unix/zerrors_darwin_arm64.go#L1459

`TCP_KEEPINTVL` is present for both `darwin-amd64` and `darwin-arm64`. You can safely use `unix.TCP_KEEPINTVL`.

2022-01-16 13:23 UTC, xiaokangwang commented on transport/internet/sockopt_darwin.go
> +				}
Your recommendation have been adapted at 406e0f7ac6614e53870687725dfc8e48a142be95.

2022-01-16 13:23 UTC, xiaokangwang commented on transport/internet/sockopt_darwin.go
> +	sysTCP_KEEPINTVL = 0x101 // nolint: revive,stylecheck
Your recommendation have been adapted at 406e0f7ac6614e53870687725dfc8e48a142be95.

2022-01-16 13:25 UTC, database64128 approved these changes

2022-01-16 13:31 UTC, merged

2022-01-22 00:07 UTC, ValdikSS commented
@xiaokangwang, thanks for the fix. I'll adapt it for #1483 and update shortly.