proxy/http: Avoid getting stuck when using server-first protocols
v2fly/v2ray-core pull request #1517
Opened 2022-01-03 15:14 UTC by lrh2000

PR #99 reduces an extra RTT when setting up the CONNECT tunnel
via http proxy, however, server-first protocols (such as MySQL)
will be unusable as v2ray keeps to wait for the client request.
This commit solves the problem by limiting the maximum waiting
time to 50 ms.

2022-01-03 15:27 UTC, database64128 requested changes
`firstPayload = make([]byte, 0)` is not needed, because you already had a nil slice with `var firstPayload []byte`.

2022-01-03 15:34 UTC, database64128 commented
Also, #1292 uses 100ms for shadowsocks outbound. Maybe we should define a constant and use the same wait time for all types of outbound?

2022-01-03 15:56 UTC, lrh2000 commented
> `firstPayload = make([]byte, 0)` is not needed, because you already had a nil slice with `var firstPayload []byte`.

> Also, #1292 uses 100ms for shadowsocks outbound. Maybe we should define a constant and use the same wait time for all types of outbound?

Thanks for your review. Actually I'm not familiar with go... and also the codebase... Any suggestions on where should I put the constant?

2022-01-03 16:43 UTC, database64128 commented
> Actually I'm not familiar with go... and also the codebase...

You did a great job already! Feel free to ask if you have any questions.

> Any suggestions on where should I put the constant?

`proxy/proxy.go` might be a good place.

2022-01-04 01:46 UTC, lrh2000 commented
Thanks @database64128 , for your nice words and kind help! I've made the constant and you may have a look at it again.

2022-01-04 04:22 UTC, database64128 approved these changes

2022-05-13 15:29 UTC, lrh2000 commented
I do not think this problem has been solved. Why did this PR get closed? It seems that I cannot even reopen it.

2022-05-13 15:34 UTC, xiaokangwang commented
I will have a look at this pr and try to merge it before next release.

2022-06-25 18:36 UTC, merged