Add trojan protocol support
v2fly/v2ray-core pull request #181
Opened 2020-09-11 02:55 UTC by maskedeken

加入trojan支持。

Inbound配置：
{
               "users": [{
                        "password": "123456"
                    }
                ],
                "fallback": {
                    "dest": "80"
                }
}

Outbound配置:
{
               "servers": [{
                        "address": "server.address",
                        "port": 443,
                        "password": "123456"
                    }
                ]
}

一般配合tls一起使用，也可以配合wss使用。
目前fallback的机制跟trojan-go一样，只是简单的把流量导向指定的地址+端口，没有像VLESS那样做复杂处理。但个人觉得fallback只是鸡肋，因为用haproxy可以直接拦截http请求，在这里把正常的http流导向正确的web服务器即可。

2020-09-11 03:46 UTC, rprx commented
回落完全采用 VLESS 的 `fallbacks` 应该更合适？（毕竟这是服务端，可以兼容客户端）

另外回落前的读取不能用 ReadFullFrom，这样防止不了逐个字节的探测。

2020-09-11 03:50 UTC, rprx commented
关于 UDP 的处理，这样做能否实现 trojan 的 FullCone？（不过似乎没有过路由？）

2020-09-11 05:45 UTC, maskedeken commented
> 
> 
> 关于 UDP 的处理，这样做能否实现 trojan 的 FullCone？（不过似乎没有过路由？）

trojan的每个udp包通过tcp传输时都带header的，里面包括地址和payload长度，是不是正跟你XUDP的想法吻合？

2020-09-11 07:11 UTC, maskedeken commented
> 
> 
> 回落完全采用 VLESS 的 `fallbacks` 应该更合适？（毕竟这是服务端，可以兼容客户端）
> 
> 另外回落前的读取不能用 ReadFullFrom，这样防止不了逐个字节的探测。

VLESS的fallback规定一定要打开tls才有效，但是我习惯把tls证书都配置在上游的haproxy

2020-09-11 07:21 UTC, rprx commented
> VLESS的fallback规定一定要打开tls才有效，但是我习惯把tls证书都配置在上游的haproxy

如果不需要判断 alpn，则 TLS 可以由其它程序处理

2020-09-11 07:25 UTC, rprx commented
> VLESS的fallback规定一定要打开tls才有效，但是我习惯把tls证书都配置在上游的haproxy

如果不用 XTLS 且不需要判断 ALPN，则 TLS 可以由其它程序处理

2020-09-11 07:27 UTC, kslr commented
别忘了添加测试

2020-09-11 07:37 UTC, rprx commented
> trojan的每个udp包通过tcp传输时都带header的，里面包括地址和payload长度，是不是正跟你改进VLESS UDP的想法吻合？

其实 XUDP 设计时就是参考了 trojan 的 UDP 结构，但这里的 header 并不简单

trojan 对 UDP 的处理是：客户端上层应用的二元组绑定服务端使用的 UDP 端口（单个隧道）

它的行为固定是：那个二元组发的 UDP 都通过固定隧道，并由服务端“和这条隧道绑定的 UDP 端口”发出，收包则是原路返回

其实这样就是 FullCone（但对路由不友好），目前 v2ray 难以做到这样，这也是迟迟不支持 trojan 的原因之一

所以这里的 UDP 行为需要被重视，希望可以尽可能做到兼容 trojan 的行为（或者后期逐步改进）

2020-09-11 08:47 UTC, maskedeken commented
> 
> 
> > trojan的每个udp包通过tcp传输时都带header的，里面包括地址和payload长度，是不是正跟你改进VLESS UDP的想法吻合？
> 
> 其实 XUDP 设计时就是参考了 trojan 的 UDP 结构，但这里的 header 并不简单
> 
> trojan 对 UDP 的处理是：客户端上层应用的二元组绑定服务端使用的 UDP 端口（单个隧道）
> 
> 它的行为固定是：那个二元组发的 UDP 都通过固定隧道，并由服务端“和这条隧道绑定的 UDP 端口”发出，收包则是原路返回
> 
> 其实这样就是 FullCone（但对路由不友好），目前 v2ray 难以做到这样，这也是迟迟不支持 trojan 的原因之一
> 
> 所以这里的 UDP 行为需要被重视，希望可以尽可能做到兼容 trojan 的行为（或者后期逐步改进）

期待你的XUDP与XTLS

2020-09-11 08:55 UTC, maskedeken commented
> 
> 
> 回落完全采用 VLESS 的 `fallbacks` 应该更合适？（毕竟这是服务端，可以兼容客户端）
> 
> 另外回落前的读取不能用 ReadFullFrom，这样防止不了逐个字节的探测。

或者我觉得，fallback作为一种新的outbound类型是否更加合适？这样各种协议都可以用这种回落

2020-09-11 14:35 UTC, rprx commented
> 期待你的XUDP与XTLS

https://github.com/rprx/v2ray-vless/releases/tag/xtls

2020-09-11 14:36 UTC, rprx commented
> 或者我觉得，fallback作为一种新的outbound类型是否更加合适？这样各种协议都可以用这种回落

稍微增强下 freedom 就可以了，但这样需要通过路由，性能会打折扣

2020-09-11 14:42 UTC, kslr commented
新建一个 fallbacks outbound 会更简单， Freedom 就不要搞得太复杂了吧，里面要过很多流程

2020-09-11 16:36 UTC, p4gefau1t requested changes
没有发现安全性方面的太大的问题，UDP 转发的逻辑可能需要重新考虑（可能需要部分修改 v2ray 架构）

2020-09-11 16:36 UTC, p4gefau1t commented on proxy/trojan/client.go
> +		if err := bufferWriter.SetBuffered(false); err != nil {
最好头部和负载一起发送，避免首包的固定长度特征

2020-09-11 16:36 UTC, p4gefau1t commented on proxy/trojan/server.go
> +	link, err := dispatcher.Dispatch(ctx, destination)
UDP Associate 请求头部携带的目的地址**不是**之后的所有 UDP 包的地址。这个连接中，接下来到来的 UDP 包的目的地址可能各不相同，应当每个包单独处理

2020-09-11 16:36 UTC, p4gefau1t commented on proxy/trojan/protocol.go
> +	_, _, err := addrParser.ReadAddressPort(&buffer, pr.Reader)
这里获得的才是这个 UDP 包实际的目的地址

2020-09-12 10:12 UTC, maskedeken commented on proxy/trojan/server.go
> +	link, err := dispatcher.Dispatch(ctx, destination)
那客户端的每个udp头的目标地址要怎么填？

2020-09-16 11:19 UTC, maskedeken commented
改为用udp.Dispatcher应该可以解决udp relay的问题

2020-09-16 11:41 UTC, Loyalsoldier commented
Please write comments or descriptions for the exported to pass the Codacy test.

2020-09-16 12:35 UTC, maskedeken commented
改用udp.Dispatcher应该可以解决udp relay的问题

2020-09-16 12:37 UTC, kslr commented
其他两个测试等我回去修一下

2020-09-16 13:58 UTC, kslr commented on proxy/trojan/client.go
> +	v := core.MustFromContext(ctx)
这个是从哪里来的

2020-09-16 15:37 UTC, maskedeken commented on proxy/trojan/client.go
> +	v := core.MustFromContext(ctx)
这个不是从context获取v2ray instance吗？

2020-09-17 01:27 UTC, maskedeken commented
> 
> 
> 建议配置应该和其他的格式相同。
> 
> Outbound
> 
> ```json
> {
>     "vnext": [
>         {
>             "address": "127.0.0.1",
>             "port": 37192,
>             "users": [
>                 {
>                     "password": "27848739-7e62-4138-9fd3-098a63964b6b",
>                 }
>             ]
>         }
>     ]
> }
> ```
> 
> Inbound
> 
> ```json
> {
>     "clients": [
>         {
>             "password": "27848739-7e62-4138-9fd3-098a63964b6b",
>         }
>     ],
>     "fallbacks": [
>         {
>             "dest": 80
>         }
>     ],
>     more...
> }
> ```

1、Outbound沿用vmess的vnext似乎不合适，所以用了和Shadowsocks一致的Servers。对于trojan出站的user配置，只要单用户就行，无需数组，所以跟Shadowsocks一样，和server配置放在一起。

2、Inbound的users配置已改用clients代替

2020-09-17 13:42 UTC, kslr commented
你在本地编译正常吗 https://dev.azure.com/xiaokangwang/V2Fly/_build/results?buildId=643&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=0db80ebc-3da9-5105-8df1-43c3063dee76

2020-09-17 14:23 UTC, maskedeken commented
> 你在本地编译正常吗 https://dev.azure.com/xiaokangwang/V2Fly/_build/results?buildId=643&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=0db80ebc-3da9-5105-8df1-43c3063dee76

本地正常。

这里显示是core.MustFromContext未定义，core包不是最核心的包吗？

2020-09-18 11:01 UTC, Loyalsoldier commented
Please fix according to linter test or you can propose a better linter settings for golangci-linter.

2020-09-20 16:06 UTC, Vigilans commented on proxy/trojan/server.go
> +package trojan
"// +build !confonly" is missing here, causing `v2ray.com/core/proxy/trojan` to be included in the build of `v2ctl`, resulting in the error from [Azure CI](https://dev.azure.com/xiaokangwang/V2Fly/_build/results?buildId=659&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=0db80ebc-3da9-5105-8df1-43c3063dee76&l=38):
```
# v2ray.com/core/proxy/trojan
proxy/trojan/server.go:50:7: undefined: core.MustFromContext
```

2020-09-20 21:31 UTC, Loyalsoldier commented
Shit. I try to fix the code according to linter results, and cherry-pick the commits to another branch, then lost the original author. How to fix this problem...?

2020-09-20 22:17 UTC, Loyalsoldier commented
Fixed the code according to linter results, mainly to check errors and skip some tests. Need to review again?

2020-09-21 08:39 UTC, Loyalsoldier commented
@maskedeken Oh man, you finally appear. Please rebase your code on master branch, format it and check the changes I made.

2020-09-21 11:00 UTC, maskedeken commented
> @maskedeken Oh man, you finally appear. Please rebase your code on master branch, format it and check the changes I made.

I have rebased the code

2020-09-21 11:31 UTC, Loyalsoldier commented
Why closed this PR?

2020-09-21 12:53 UTC, maskedeken commented
> 
> 
> Why closed this PR?

by mistake. Sorry about that

2020-09-21 15:46 UTC, rprx commented
关于回落，“个人觉得fallback只是鸡肋，因为用haproxy可以直接拦截http请求，在这里把正常的http流导向正确的web服务器即可”是不对的，因为要保证首包长度不够或认证失败的流量也回落到 web 服务器。

目前 VLESS 的 fallbacks 回落分流非常强大，但针对协议结构做了些定制，若把它变成一个出站再经过路由，性能上会打一些折扣。所以建议完整复制 VLESS 的回落分流机制（以后可以放到 common），这样会更有吸引力，用户还没有学习成本。

2020-09-24 20:21 UTC, kslr approved these changes
简单裸 TCP 和 TLS 测试工作正常 
core <-> core   core <-> trojan-go(qv)

p.s 4.29 前不要和并

2020-09-26 15:31 UTC, merged

2020-09-26 15:32 UTC, kslr commented
![sticker](https://user-images.githubusercontent.com/5516323/91638289-edffeb00-ea40-11ea-84ea-98c2d70efb1d.png)

2020-10-02 08:18 UTC, NutterChen commented
HandlerService在一个入站代理中添加或删除一个用户是否已经支持trojan协议？
今天测试了下，无法添加，暂不知是我的代码问题还是尚不支持

目前使用的是https://github.com/v2fly/v2ray-core/commit/cde63bfac1241a8e410e8a89cd27632b95c85723