Shadowsocks2022 Client Implementation Improvements
v2fly/v2ray-core pull request #2770
Opened 2023-11-20 18:33 UTC by xiaokangwang

1. Added UDP Replay Detection
2. Added UDP Processor State Cache
3. Added More Detailed Output for Time Difference Error

2023-11-21 03:20 UTC, database64128 requested changes

2023-11-21 03:20 UTC, database64128 commented on proxy/shadowsocks2022/client_session.go
A lot of contention on `sessionMap`. The lock is taken once per packet on the encode path, and twice per packet on the decode path.

2023-11-21 03:20 UTC, database64128 commented on proxy/shadowsocks2022/udp_aes.go
> +		// to client session id.
The server session ID is random for a reason.

When a server restarts and receives packets from a client session that has been there since before the restart, it cannot restore the previous server session state, and must create a new server session.

If you use an algorithm that generate stable server session IDs from client session IDs, the new server session subkey will be the same as the one before restarting. But the nonce counter still starts from 0. This is nonce reuse with the same key. AES-GCM breaks catastrophically in this case.

2023-11-21 17:50 UTC, xiaokangwang commented on proxy/shadowsocks2022/udp_aes.go
> +		// to client session id.
Yes, this this true if server restarts in less than 1 minutes. I suggests modify spec `Servers use client session IDs to identify UDP sessions. For server-to-client messages, a different set of session ID and packet ID is used, and may be referred to as server session ID and server packet ID. Servers MUST not use client session IDs as server session IDs.` and require Servers to generate server session ID randomly.

2023-11-22 06:58 UTC, database64128 requested changes

2023-11-22 06:58 UTC, database64128 commented on proxy/shadowsocks2022/client_session.go
> +		readChan:               make(chan *UDPResponse, 16),
What's the rationale behind choosing 16 as the channel buffer size? 16 looks a bit too small to me.

Both shadowsocks-rust and shadowsocks-go use 1024 as the channel buffer size. In this case, 1024 slots only takes up 8192 bytes on 64-bit platforms.

2023-11-22 06:58 UTC, database64128 commented on proxy/shadowsocks2022/client_session.go
> +				}
It's fine to delete k-v pairs from a map while iterating over it. There's no need to cache the keys to delete in a separate slice.

The replay window during a server session change is only 60 seconds. Why does it cache the state for 125 seconds?

2023-11-22 18:06 UTC, xiaokangwang commented on proxy/shadowsocks2022/client_session.go
> +		readChan:               make(chan *UDPResponse, 16),
I have increased this value to 128. V2Ray may have many other buffers in addition to this one, increasing buffer futher will just increase delay and won't help with burst tranmissions.

2023-11-22 18:10 UTC, xiaokangwang commented on proxy/shadowsocks2022/client_session.go
> +				}
I have adjusted this value to 65 seconds and removed mark and remove for Server Session ID.

2023-11-22 18:11 UTC, xiaokangwang commented
I have got another round of edit. Please have a look and please let me know if there is any other suggestions before you consider this implementation spec compliant.

2023-11-23 01:57 UTC, database64128 commented on proxy/shadowsocks2022/udp_aes.go
> +		// to client session id.
Done in Shadowsocks-NET/shadowsocks-specs#7

2023-11-23 03:25 UTC, database64128 approved these changes
Thank you for addressing my feedback. LGTM now.

2023-11-24 00:40 UTC, merged