[BUGFIX] Remove magic value 108, fix domainsocket path length overflow in darwin
v2fly/v2ray-core pull request #438
Opened 2020-11-20 10:22 UTC by chinsyo

修改代码中unix domain socket长度限制未做校验，截取前108byte的问题。
在macos/freebsd/openbsd等系统中，domain socket path长度限制为104。

macos可通过如下终端命令验证。
```bash
# go doc golang.org/x/sys/unix.RawSockaddrUnix
package unix // import "golang.org/x/sys/unix"

type RawSockaddrUnix struct {
	Len    uint8
	Family uint8
	Path   [104]int8
}
```

seealso:

- [why-is-socket-path-length-limited-to-a-hundred-chars](https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars)

2020-11-20 13:01 UTC, kslr commented
请按照 codacy 添加注释

2020-11-20 13:03 UTC, chinsyo commented
好的，到家就加

发自我的iPhone


------------------ Original ------------------
From: Kslr <notifications@github.com&gt;
Date: Fri,Nov 20,2020 9:02 PM
To: v2fly/v2ray-core <v2ray-core@noreply.github.com&gt;
Cc: Chinsyo <619549705@qq.com&gt;, Author <author@noreply.github.com&gt;
Subject: Re: [v2fly/v2ray-core] [BUGFIX] Remove magic value 108, fix domainsocket path length overflow in darwin (#438)

2020-11-20 13:25 UTC, lucifer9 requested changes
这里的逻辑是 c.Abstract && c.Padding 的情况下才会用满108字节。而只有Linux才支持 Abstract Unix Domain Socket。当然确实这里没考虑到用户不小心写错配置的情况，保险起见的话，加上对runtime的判断会好些。这里Linux是唯一一个特殊的，只需要判断它就行。可以参考system_listener.go的写法。例如改为 runtime.GOOS == "linux" && c.Abstract && c.Padding。

2020-11-20 14:04 UTC, chinsyo commented
> 这里的逻辑是 c.Abstract && c.Padding 的情况下才会用满108字节。而只有Linux才支持 Abstract Unix Domain Socket。当然确实这里没考虑到用户不小心写错配置的情况，保险起见的话，加上对runtime的判断会好些。这里Linux是唯一一个特殊的，只需要判断它就行。可以参考system_listener.go的写法。例如改为 runtime.GOOS == "linux" && c.Abstract && c.Padding。

有没有可能用户设置的domain socket path长度直接超过104/108在对应平台

2020-11-20 14:31 UTC, lucifer9 commented
> > 这里的逻辑是 c.Abstract && c.Padding 的情况下才会用满108字节。而只有Linux才支持 Abstract Unix Domain Socket。当然确实这里没考虑到用户不小心写错配置的情况，保险起见的话，加上对runtime的判断会好些。这里Linux是唯一一个特殊的，只需要判断它就行。可以参考system_listener.go的写法。例如改为 runtime.GOOS == "linux" && c.Abstract && c.Padding。
> 
> 有没有可能用户设置的domain socket path长度直接超过104/108在对应平台

可能性肯定是有的，不过应该不大。如果用户给了个太长的path，那go在bind的时候也会报错的，一样会中断执行。或者就把这个检查往前提，在parse配置文件的时候就检查？不过严格来说应该没太大必要。就像没有太大必要检查设置里面指定的log文件名是不是会太长一样。

2020-12-18 00:57 UTC, Loyalsoldier commented
Thanks for your work. According to the above discussion, this PR will not be merged.

2020-12-18 00:57 UTC, closed without merging