Feat: add queryStrategy option for DNS
v2fly/v2ray-core pull request #749
Opened 2021-03-07 22:51 UTC by Loyalsoldier

2021-03-08 02:00 UTC, kslr commented on features/dns/client.go
> +
设置项放到这里是不是有点奇怪

2021-03-08 02:30 UTC, Loyalsoldier commented on features/dns/client.go
> +
不然怎么动态设置 DNS Client 的查询参数呢？🤔

2021-03-08 17:49 UTC, xiaokangwang requested changes
这个修改太魔改了，如果你需要这个功能我可以帮你写，但是如果你写的话需要保证

* 不要进行破坏性修改：不要修改已有接口，保证任何一个实现已有接口的第三方实现可以继续正常运行
* 不要破坏兼容性： reserve的字段不能再被使用。

之前的魔改修改接口为我就很难受，正准备想办法给回滚回去。

2021-03-08 17:49 UTC, xiaokangwang commented on features/dns/client.go
> +
禁止修改V2Ray的v2ray:api:stable接口。你加接口的话也要保证对于没实现这个接口的实现也可以运行。

2021-03-08 17:49 UTC, xiaokangwang commented on app/dns/config.proto
> +  QueryStrategy query_strategy = 7;
禁止使用reserved的字段，新加一个吧

2021-03-08 17:51 UTC, xiaokangwang commented
这里正确的实现方法是新加一个接口，然后用类型断言来确定是否实现了新的接口，如果实现了就用新接口

2021-03-09 00:28 UTC, Loyalsoldier commented
> 这里正确的实现方法是新加一个接口，然后用类型断言来确定是否实现了新的接口，如果实现了就用新接口。而不是通过改已有接口来实现功能。如果需要的话我可以直接连上次的因为fakedns什么的改的接口一起给改回去。

请展示真正的技术 😋 😀

2021-03-09 11:39 UTC, xiaokangwang commented
好！昨天那么说有点抱歉，实在是看见这种修改有点难受上头了。。。

2021-03-18 04:41 UTC, closed without merging