Fix: add keep alive request duration to configs
v2fly/v2ray-core pull request #962
Opened 2021-05-02 19:17 UTC by therealak12

Trying to solve [this](https://github.com/v2ray/v2ray-core/issues/2564).

2021-05-02 20:08 UTC, xiaokangwang requested changes
If I understand this correctly, TCP_KEEPINTVL is a TCP specific option. You should not set it without checking the type of the socket. 

You can either change the code, let me to fix this and merge, or justify your design.

2021-05-02 20:14 UTC, therealak12 commented
You're right. I'll try to find a more general approach for setting the keep-alive duration.
If you are going to fix it before me, I would appreciate (solving this problem is by far more important than my contribution).

2021-05-04 21:27 UTC, xiaokangwang commented
I will make necessary modification and merge it.

2021-05-04 21:47 UTC, merged

2021-05-07 06:17 UTC, ValdikSS commented
Is this modification only for Linux sockets, not for other OS?

2021-05-07 07:04 UTC, chromer030 commented
how we should set it in configs ?

2021-05-07 07:05 UTC, Loyalsoldier commented
> Is this modification only for Linux sockets, not for other OS?

Only for Linux.

2021-05-07 07:06 UTC, Loyalsoldier commented
> how we should set it in configs ?

https://www.v2fly.org/config/transport.html#sockoptobject

2021-08-29 18:34 UTC, ValdikSS commented
Does **not** seem to be fixed in v2fly v4.41.1.

Test 1:
1. Run v2fly v4.41.1 with default config.json (remove `geoip:private` block first)
2. start `nc -l -p 4141`
3. execute `curl --proxy socks5://127.0.0.1:1080 127.0.0.1:4141`

Result: 15 second keep-alive *from v2fly to socks client* (1080 → client source port)

Adding `"streamSettings": {"sockopt": {"tcpKeepAliveInterval": 900}},` to both `inbounds` and `outbounds` directives did not change anything.

2021-08-29 18:38 UTC, ValdikSS commented
This change is for `applyOutboundSocketOptions`, however the main issue is with inbound (listening) sockets which are used for client connections and client-v2fly transmission from the server standpoint.

2021-09-18 01:33 UTC, ValdikSS commented
This commit changes the wrong parameter. `TCP_KEEPIDLE` should be changed, not `TCP_KEEPINTVL`.

>TCP_KEEPIDLE (since Linux 2.4)
>        The  time  (in  seconds)  the  connection needs to remain idle before TCP starts sending keepalive probes, if the socket option SO_KEEPALIVE has been set on this socket.  This option should not be used in code intended to be portable.
>
>TCP_KEEPINTVL (since Linux 2.4)
>        The time (in seconds) between individual keepalive probes.  This option should not be used in code intended to be portable.

Go sets both TCP_KEEPINTVL and TCP_KEEPIDLE to 15. Leaving TCP_KEEPINTVL to 15 looks fine to me (Linux default is 75). TCP_KEEPCNT is not changed and kept to standard 9, so 15*9 = 135 seconds before connection teardown, after TCP_KEEPIDLE had an effect.