feat: update bootstrapdns with `network`
v2fly/v2ray-core pull request #966
Opened 2021-05-04 02:50 UTC by rurirei

this makes the bootstrap dialer on both network tcp or udp.

2021-05-04 06:50 UTC, rurirei commented
@CalmLong opinion wanted.

2021-05-04 07:05 UTC, CalmLong approved these changes

2021-05-04 07:06 UTC, CalmLong commented
是需要通过外部来更改 bootstrapDNS 吗

2021-05-04 07:08 UTC, rurirei commented
@CalmLong thanks for approving. you can find a example in _test.go

2021-05-04 07:17 UTC, CalmLong commented
只是这里是替换了 `net.DefaultResolver`，UseAlternativeBootstrapDNS 改为 UseCustomBootstrapDNS 会不会好一些

2021-05-04 07:21 UTC, rurirei commented
@CalmLong the naming is referenced `internet.UseAlternativeSystemDialer` in system_dialer.go

2021-05-04 07:25 UTC, CalmLong commented
ok

2021-05-04 11:58 UTC, CalmLong approved these changes

2021-05-04 12:07 UTC, CalmLong commented
Android 的我觉得没问题，剩下的由管理看下吧

2021-05-04 12:53 UTC, xiaokangwang requested changes
这个修改改变了V2Ray的公开接口，影响了其其他系统的行为。 需要进一步讨论和改进。

请使用您熟悉的语言来描述您进行这个理由，以及为什么想实现这个功能。

这个修改可能需要一段时间才能完成处理，建议先通过自行打补丁的方式来使用这些修改提供的功能。

2021-05-04 12:53 UTC, xiaokangwang commented on transport/internet/system_dialer.go
> +		Resolver:  NewDNSResolver(),
这个是一个针对 Adnroid 系统的修改，但是修改了在其他平台下的逻辑。

2021-05-04 12:53 UTC, xiaokangwang commented on transport/internet/system_dialer.go
> +		Resolver:  NewDNSResolver(),
这个设计没有考虑到是使用V2Ray自己的DNS系统进行解析的可能。

2021-05-04 12:53 UTC, xiaokangwang commented on transport/internet/system_dns.go
> +var NewDNSResolver DNSResolverFunc = func() *net.Resolver {
这个公开API的设计无法满足根据状态自动改变解析器，感觉未来要改。因此不应该成为一个公开的接口
这个默认的解析器修改了之前的默认的行为，不太建议。

2021-05-04 12:53 UTC, xiaokangwang commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
这里有了一个不可配置的DNS服务器。这个已经被 @nekohasekai  投诉了。 还没来及改。 如果修改的话想一次改掉。

2021-05-04 12:55 UTC, rurirei commented
i've using this way (the systemDialer with customized and specified Resolver) for a long while (for windows and android as well), as i thought the way to override net.DefaultResolver is not a good idea. i'm glad to see any review, thanks all.

2021-05-04 12:59 UTC, xiaokangwang commented
I suppose you have used V2Ray as a library. Why not use UseAlternativeSystemDialer to override the DNS resolution behavior. It provide a superset of what UseAlternativeBootstrapDNS could provide. Is there something you cannot achieve with a custom SystemDialer?

2021-05-04 13:01 UTC, rurirei commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
do you say a configurable dns address, not default "8.8.8.8:53"? this is a TODO item.

2021-05-04 13:06 UTC, xiaokangwang commented
I also believe override net.DefaultResolver is not a good idea. And I am looking to improve it. However, I still don't know the exact thing you are attempting to achieve. 

Are you using V2Ray as standalone program in Android, or as a library?

2021-05-04 13:22 UTC, rurirei commented
> I suppose you have used V2Ray as a library. Why not use UseAlternativeSystemDialer to override the DNS resolution behavior. It provide a superset of UseAlternativeBootstrapDNS's function. Is there something you cannot achieve with a custom SystemDialer?

internet.SystemDialer contains much private numbers, there leaves matters if one need to do a custom dialerResolver only.

i did a small change for net.DefaultResolver at this pull request, though i do not satisfied with that way, so i wrote a new internet/system_dns.go interface.

i wanna know how the specified dialer.Resolver affects the platform compatibility.

2021-05-04 13:26 UTC, CalmLong commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
> 这里有了一个不可配置的DNS服务器。这个已经被 @nekohasekai 投诉了。 还没来及改。 如果修改的话想一次改掉。

这话我就不爱听了，做周边就可以投诉，那之前安卓跑二进制遇到 DNS 解析的问题时也没见得有人就出来改一下 v2ray/v2ray-core/issues/1909

再说这个更改虽然不优雅，但是

仅在安卓系统上生效
不会影响 V2Ray 内置的 DNS

也就是说只有 V2Ray 内置的 DNS 不存在时才会起作用

况且之前我的想法是从内置的 DNS 配置中取一个放到这里，要是没有配置再设置一个，但是那样很麻烦，而且硬编码也是和 @kslr 商量过的

如果说真的影响了安卓 App 的开发，获取到系统的 DNS 塞到内置的 DNS 里不就行了么，虽然还是用了 V2Ray 内置的 DNS，但是 DNS 地址还是用的系统的又有什么关系

2021-05-04 13:49 UTC, xiaokangwang commented
When you build with CGO, Go will use getaddrinfo to retrieve DNS information on Linux and similar system level primitive on other systems (https://golang.org/pkg/net/#hdr-Name_Resolution).  Sometime only the system resolver works.

By using PreferGo: true, on all platforms, you have changed the default behavior for V2Ray build with CGO.

2021-05-04 13:52 UTC, xiaokangwang commented
You can find examples of setting dialer here. https://github.com/nekohasekai/AndroidLibV2rayLite/blob/6d7de657ad40765a50278c1dffbf2d4e27c1bd9f/VPN/vpnservice_support.go

You don't need to support every options available to get it working.

2021-05-04 14:00 UTC, xiaokangwang commented
You can tell me in detail the root reason you are attempting this change. 

What kind of environment you are using this in?

Are you using V2Ray as standalone program in Android, or as a library?

If you are using it as a standalone program, please provide full configure file.  
If you are using it as a library, please provide a link of code.

What is the thing you are expecting, and what unexpected thing happened?

2021-05-04 14:02 UTC, rurirei commented
a revert is done here.

2021-05-04 14:08 UTC, xiaokangwang commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
之前之前修改已经解决了不能用的问题了。现在进一步的修改应该彻底的解决掉这个问题。如果仅仅影响Android的话倒是没有问题，但是实际上这个PR还产生了对其他平台的修改。我要求修改是基于这个PR产生了对于其他的平台的修改以及新建了一个不必要的公开API，而不是因为改了Android的部分。

2021-05-04 14:11 UTC, xiaokangwang commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
如果仅仅是更新了Android的部分的话当然是没有问题的。

2021-05-04 14:14 UTC, xiaokangwang commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
https://github.com/v2fly/v2ray-core/pull/966/files/56614cca69460195b621bed43bdfb4d2fd55aa14#diff-fffd9eea78d4a3cf715aa4d82845bf5e54711bd5f314aadccb4049014e198149 https://github.com/v2fly/v2ray-core/pull/966/files/56614cca69460195b621bed43bdfb4d2fd55aa14#diff-6a7def47c7edb3ca1b96dbdd19bd3d8583ba03047e265846018c0b357aef73db

2021-05-04 14:14 UTC, xiaokangwang commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
这个PR在我当时处理的时候还产生对其他平台的逻辑的修改。

2021-05-04 14:24 UTC, xiaokangwang commented on transport/internet/system_dns.go
> +var NewDNSResolver DNSResolverFunc = func() *net.Resolver {
There is a better effort attempt to reduce the amount of API change. This is a API change for using V2Ray as library, the user of library can always patch V2Ray so there is no need to introduce a API that will change later.

2021-05-04 14:37 UTC, xiaokangwang approved these changes
OK，non-android shouldn't be influence by this change now. I will merge this before next release.

2021-05-04 14:40 UTC, xiaokangwang commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
> > 这里有了一个不可配置的DNS服务器。这个已经被 @nekohasekai 投诉了。 还没来及改。 如果修改的话想一次改掉。
> 
> 这话我就不爱听了，做周边就可以投诉，那之前安卓跑二进制遇到 DNS 解析的问题时也没见得有人就出来改一下 [v2ray/v2ray-core/issues/1909](https://github.com/v2ray/v2ray-core/issues/1909)
> 
> 再说这个更改虽然不优雅，但是
> 
>     * 仅在安卓系统上生效
> 
>     * 不会影响 V2Ray 内置的 DNS
> 
> 
> 况且之前我的想法是从内置的 DNS 配置中取一个放到这里，要是没有配置再设置一个，但是那样很麻烦，而且硬编码也是和 @kslr 商量过的
> 
> 如果说真的影响了安卓 App 的开发，获取到系统的 DNS 塞到内置的 DNS 里不就行了么，虽然还是用了 V2Ray 内置的 DNS，但是 DNS 地址还是用的系统的又有什么关系


当时那个修改没有问题，毕竟解决了不能用的问题。现在想做的是看看能不能彻底的解决这个问题。

2021-05-04 14:43 UTC, xiaokangwang commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
如果不能长久的解决这个问题，就不应该去产生会让别人的配置炸掉的情况。我这里的这个高标准是因为这个PR在当时产生了会炸掉一些人设置的情况，所以要一次把问题解决。

2021-05-04 14:43 UTC, xiaokangwang commented
> a revert is done here.

You can tell me in detail the root reason you are attempting this change.

What kind of environment you are using this in?

Are you using V2Ray as standalone program in Android, or as a library?

If you are using it as a standalone program, please provide full configure file.
If you are using it as a library, please provide a link of code.

What is the thing you are expecting, and what unexpected thing happened?

2021-05-04 14:44 UTC, xiaokangwang commented
I wants to know the exact reason you wants to make this change so that I can have a long term solution for you.

2021-05-04 14:48 UTC, rurirei commented
> I wants to know the exact reason you wants to make this change so that I can have a long term solution for you.

https://github.com/v2fly/v2ray-core/pull/966#issue-629480981

2021-05-04 14:50 UTC, xiaokangwang commented
> > I wants to know the exact reason you wants to make this change so that I can have a long term solution for you.
> 
> [#966 (comment)](https://github.com/v2fly/v2ray-core/pull/966#issue-629480981)

This is what you have changed, not why you have changed it.

If you are using it as a standalone program, please provide full configure file.
If you are using it as a library, please provide a link of code.

What is your exact use case?

2021-05-04 14:51 UTC, xiaokangwang commented
I wants to find a permanent solution to your problem, and add it to the to do list

2021-05-04 14:53 UTC, rurirei commented
@xiaokangwang 
1. as library (AndroidLibV2ray based)
2. i need to override the dns address "8.8.8.8:53"

2021-05-04 14:58 UTC, xiaokangwang commented
> @xiaokangwang
> 
>     1. as library (AndroidLibV2ray based)
> 
>     2. i need to override the dns address "8.8.8.8:53"

OK, I will work toward a permanent solution to your issue.  Can you give me a link of your client. This can help me assign priority.

2021-05-04 15:10 UTC, rurirei commented
@xiaokangwang in fact internet.UseAlternativeSystemDialer() is not necessary for AndroidLibV2ray (method fdConn in AndroidLibV2ray is not necessary). i need a method to make a custom systemDialer.Resolver only, rather than to override the systemDialer (what method fdConn do). the reverted "systemDNS for systemDialer" commits is what i really wanted.

you can kindly do solve the problem exists pastly. thanks.

2021-05-04 15:11 UTC, xiaokangwang commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
@CalmLong 给我的投诉是说现在的思路不够好，不是说你当时不应该改。当时的修改确实解决了一个问题，而且没有产生不好的影响，因此是很好的。我是希望能找到更好的改变的方法。 如果让你产生了误会， 我对其深表歉意。

2021-05-04 15:17 UTC, xiaokangwang commented
OK, 这样子的话对其他系统

> @xiaokangwang in fact internet.UseAlternativeSystemDialer() is not necessary for AndroidLibV2ray (method fdConn in AndroidLibV2ray is not necessary for work). i need a method to make a custom systemDialer.Resolver only, rather than to override the systemDialer (what method fdConn do). the reverted "systemDNS for systemDialer" commits is what i really wanted.
> 
> you can kindly do solve the problem exists pastly. thanks.

You don't have to convert this to a draft.

I will merge this PR as a temporary solution. You can use this temporary solution today while I working on a permanent one.

Please mark this PR as ready for review so that I can merge it.

2021-05-04 15:20 UTC, xiaokangwang commented
Ok, I will merge this before next release.

2021-05-04 15:40 UTC, xiaokangwang commented on transport/internet/system_dns_android.go
> +				const systemDNS = "8.8.8.8:53"
> > 这里有了一个不可配置的DNS服务器。这个已经被 @nekohasekai 投诉了。 还没来及改。 如果修改的话想一次改掉。
> 
> 这话我就不爱听了，做周边就可以投诉，那之前安卓跑二进制遇到 DNS 解析的问题时也没见得有人就出来改一下 [v2ray/v2ray-core/issues/1909](https://github.com/v2ray/v2ray-core/issues/1909)
> 
> 再说这个更改虽然不优雅，但是
> 
>     * 仅在安卓系统上生效
> 
>     * 不会影响 V2Ray 内置的 DNS
> 
> 
> 况且之前我的想法是从内置的 DNS 配置中取一个放到这里，要是没有配置再设置一个，但是那样很麻烦，而且硬编码也是和 @kslr 商量过的
> 
> 如果说真的影响了安卓 App 的开发，获取到系统的 DNS 塞到内置的 DNS 里不就行了么，虽然还是用了 V2Ray 内置的 DNS，但是 DNS 地址还是用的系统的又有什么关系

这个问题我会想办法解决的，非常抱歉。。。。

2021-05-04 21:22 UTC, merged

2021-05-05 06:49 UTC, xiaokangwang commented
@rurirei I am sorry to inform you that because of some of the recent PR you have made to this repo. ( https://github.com/v2fly/v2ray-core/pull/852 https://github.com/v2fly/v2ray-core/pull/966 https://github.com/v2fly/v2ray-core/pull/852 https://github.com/v2fly/v2ray-core/pull/831 ) I have requested team member to consider your PR ineligible for merge by organization members. A review from the organization owner will be required to merge your further PR. This status may be waivered later.

You have repeatably sent Pull Request to upstream to get your code pass compilation without understanding the implication and consequence of such change. 

I am committed to helping you with achieving what you want to do without compromising the code quality, standard, and objective of V2Ray.

2021-05-05 07:19 UTC, rurirei commented
@xiaokangwang i'm sorry for bad codes.

2021-05-05 07:25 UTC, xiaokangwang commented
> @xiaokangwang i'm sorry for bad codes.

Don't worry, we have all been inexperienced at some point, and I have made a lot of mistakes in the past as well. It is not your fault. I just wants to reduce the revert action whenever possible. 

But, I am here to help you! I can discuss your change with you and get things working together. Just make sure don't make any major change before asking, you might waste your time and I will feel really bad to request you to redo the work.

2021-05-05 07:28 UTC, rurirei commented
> I just wants to reduce the revert action whenever possible.

i'm glad to see your help of course.

p.s. what i did is just pull request, not commiting? 😢

2021-05-05 07:29 UTC, xiaokangwang commented
Yes, but if someone else merged your code without the necessary review, I will have to revert it at a later point.

2021-05-05 07:32 UTC, rurirei commented
got it. **draft** is the good idea.

2021-05-05 07:35 UTC, xiaokangwang commented
And, you can request for review at any point. ^_^ I am ready when you are.